# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michal/Mandelbrot-Set

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michal/Mandelbrot-Set

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michal/Mandelbrot-Set/CMakeFiles /home/michal/Mandelbrot-Set/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michal/Mandelbrot-Set/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slave

# Build rule for target.
slave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave
.PHONY : slave

# fast build rule for target.
slave/fast:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/build
.PHONY : slave/fast

#=============================================================================
# Target rules for targets named master

# Build rule for target.
master: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 master
.PHONY : master

# fast build rule for target.
master/fast:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/build
.PHONY : master/fast

master.o: master.c.o

.PHONY : master.o

# target to build an object file
master.c.o:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/master.c.o
.PHONY : master.c.o

master.i: master.c.i

.PHONY : master.i

# target to preprocess a source file
master.c.i:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/master.c.i
.PHONY : master.c.i

master.s: master.c.s

.PHONY : master.s

# target to generate assembly for a file
master.c.s:
	$(MAKE) -f CMakeFiles/master.dir/build.make CMakeFiles/master.dir/master.c.s
.PHONY : master.c.s

slave.o: slave.c.o

.PHONY : slave.o

# target to build an object file
slave.c.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave.c.o
.PHONY : slave.c.o

slave.i: slave.c.i

.PHONY : slave.i

# target to preprocess a source file
slave.c.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave.c.i
.PHONY : slave.c.i

slave.s: slave.c.s

.PHONY : slave.s

# target to generate assembly for a file
slave.c.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave.c.s
.PHONY : slave.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... slave"
	@echo "... master"
	@echo "... master.o"
	@echo "... master.i"
	@echo "... master.s"
	@echo "... slave.o"
	@echo "... slave.i"
	@echo "... slave.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

